### ISSUE TITLE
[K2 Partnering] Oportunidade remota - Desenvolvedor ioS Sênior

### ISSUE THREAD

**Issue by natashacosta** [remotejobsbr/remote-jobs-client#14]
Sou Tech Recruiter na K2 Partnering, consultoria de recrutamento e seleção britânica, presente em 19 países, há mais de 20 anos.

**Desenvolvedor iOS Senior**
Atuação remota
PJ, parceria com a K2
Tempo de duração do projeto: 06 meses + possibilidade de renovação via K2 ou efetivação CLT pelo cliente
Data de início do candidato no projeto: 07/10

Skill Eliminatório:
Desenvolvedor iOS Sênior para atuar em cliente final do cliente
Necessário nível Sênior em desenvolvimento iOS Nativo.
Projeto será feito remotamente, porém em horário comercial, 8h/dia.

Tem interesse?
Me procura!

ncosta@k2partnering.com

**Comment by IsTheJack** [comment]
Oi, @natashacosta. Esse repositório é apenas do site do remote jobs. Caso você queira que sua vaga apareça no site, por favor, crie uma issue nesse repositório: https://github.com/CocoaHeadsBrasil/vagas/issues
