### ISSUE TITLE
Criar CONTRIBUTING.md

### ISSUE THREAD

**Issue by IsTheJack** [remotejobsbr/remote-jobs-client#5]
O projeto ainda está sem um guia definido para ajudar no processo de colaboração.

Qualquer dica de 'template' de arquivo de contributing é bem vindo.

**Comment by IsTheJack** [comment]
Arquivo de contributing ja foi criado, mas ainda falta desenvolve-lo com uma documentação sobre upstream e algumas regras de conduta.

**Comment by nelsonmfinda** [comment]
@IsTheJack  Como vai?
Regras de conduta, tipo padrão de código, lint, e etc?

**Comment by joaosantana** [comment]
Olá, @IsTheJack . Acabo de enviar o PR  #13  para trabalhar com o projeto a atualização do CONTRIBUTING.md. Fico à disposição para receber sugestões sobre como completá-lo.
