### ISSUE TITLE
Layout quebrando em algumas vagas

### ISSUE THREAD

**Issue by williangd** [remotejobsbr/remote-jobs-client#9]
Em algumas vagas o layout fica quebrado. 

Segue um exemplo:

![layout](https://user-images.githubusercontent.com/16259047/51692323-d39f9900-1fe3-11e9-8bdf-002fbe0e1d5f.png)

**Comment by IsTheJack** [comment]
@williangd Você pode verificar se esse problema foi resolvido? Deixarei a issue aberta mais alguns dias antes de fechar, mas você é livre pra fecha-la caso o seu teste de validação seja positivo. :D

**Comment by williangd** [comment]
Foi resolvido sim. :D
